:Author: Lot Amoros
:Email: hola@dronecoria.org
:Date: 13/07/2021
:Revision: version#
:License: GPL v3

= Project: {Project}

Our Open Source Seed Coating Machine, is a system created with accesible technology, which covers the needs of a small and medium scale seed coating project. It is part of Dronecoria.
Is composed by an arduino, an air compressor, a concrete mixer, and the water and powder micro pulverization systems.
For the micropulverization we use a micropulverizer of taladrine and the powder feeder we use a 3Dprinted mechanism that uses venturi effect to propulse the powder to the tube.

== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 SeedCoatingController                => Arduino sketch folder
  ├── SeedCoatingController.ino       => main Arduino file
  ├── thingProperties.h               => Arduino IOT link files
  ├── arduino_secrets.h               => Wifi passwords
  └── ReadMe.adoc                     => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact Dronecoria team.

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| A1 | Arduino Iot    | 1  | 10      
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
