// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = "6a11e07e-a0df-4612-b8d6-41e3dc5c0c59";

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onNumberRepetitionsChange();
void onMsCloseChange();
void onMlmsRelationChange();
void onMsOpenChange();

int numberRepetitions;
int msClose;
float mlmsRelation;
int msOpen;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(numberRepetitions, READWRITE, ON_CHANGE, onNumberRepetitionsChange);
  ArduinoCloud.addProperty(msClose, READWRITE, ON_CHANGE, onMsCloseChange);
  ArduinoCloud.addProperty(mlmsRelation, READWRITE, ON_CHANGE, onMlmsRelationChange);
  ArduinoCloud.addProperty(msOpen, READWRITE, ON_CHANGE, onMsOpenChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
